[project]
name = "nghiango-adb-auto"
version = "0.0.1"
dependencies = [
    "pure-python-adb",
    "PyQt6",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
adb_auto = "adb_auto:main"
